### ISSUE TITLE
your first issue

### ISSUE THREAD

**Issue by GantMan** [silasjmatson/motion-fb#1]
get a better gem name :P 

I keeed I keed.   But seriously, better name... just joking... but ...

**Comment by silasjmatson** [comment]
_dutifully ignores trollishness of comment_

Thanks for noticing! If you have any ideas, let me know.

**Comment by GantMan** [comment]
this is what I'm here for :)

![image](https://cloud.githubusercontent.com/assets/997157/9779276/c6c799a0-573f-11e5-9aad-5506aeba3f15.png)
